<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvrvk1W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvrvk1W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWvrvk1W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWvrvk1W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWvrvk1W\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wvrvk1W',
    'container.build_id' => '5175c744',
    'container.build_time' => 1587480756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvrvk1W');
