<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExiosCy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExiosCy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExiosCy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExiosCy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerExiosCy\App_KernelDevDebugContainer([
    'container.build_hash' => 'ExiosCy',
    'container.build_id' => '0e6b0726',
    'container.build_time' => 1587481155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExiosCy');
